### ISSUE TITLE
CMake Error causing Incomplete configuration

### ISSUE THREAD

**Issue by henryfhq** [NickL77/RPLidar_Hector_SLAM#7]
Hi, I'm trying to install the RPLidar_Hector_SLAM and I have encountered an Error after downloading the ROS and this error appeared:

![Screenshot from 2020-05-12 18-08-54](https://user-images.githubusercontent.com/64243957/81671625-c24dfa80-947b-11ea-97d9-a74c9251bc4d.png)

I'm using Ubuntu 18.04 on my Jetson Nano, ROS Version is Melodic. 

Idk is it something wrong with what I did or is there anything got to do with the dependency? 

Thanks

**Comment by NickL77** [comment]
The issue is probably that the libraries in this repository are for ROS Kinetic. You can either downgrade ROS or install the appropriate `hector_slam` and `rplidar` packages. If choose to stay on Melofic and you run into issues where frame names are off, you can take a look at this [resource](https://hackaday.io/project/7284-oscar-omni-service-cooperative-assistant-robot/log/26164-first-foray-into-ros) that is listed in the README.

**Comment by henryfhq** [comment]
@NickL77 Somehow I solved the issue by doing the following:

1. Downloading vision_opencv (https://github.com/ros-perception/vision_opencv.git)
2. Copy and paste cv_bridge file to the source file of the catkin workspace
3. Also, ensure that the ros-melodic-vision-opencv and ros-melodic-cv-bridge 
4. Finally, run catkin_make. 

Thank you for your suggestions and trying your best to solve the issue.

**Comment by henryfhq** [comment]
Hereby declare that the issue is now closed
